#!/bin/bash

LIMIT=$1

simspark >/dev/null 2>&1 &
export SIMSPID=$!
rcssmonitor3d >/dev/null 2>&1 &
export RCSSPID=$!

echo -e "simspark has pid: $SIMSPID\nrcssmonitor3d has pid: $RCSSPID"

if [ "x$LIMIT" != "x" ]
then
    echo "setting cpulimit to $LIMIT"
    cpulimit -p $SIMSPID -l $LIMIT -z >/dev/null 2>&1 &
    cpulimit -p $RCSSPID -l $LIMIT -z >/dev/null 2>&1 &
fi

echo -en "\033[31m"
read -p "press enter to kill the server" -s TMP
echo -e "\033[0m"

if kill -0 $SIMSPID >/dev/null 2>&1
then
    echo "killing simspark"
    kill -9 $SIMSPID
fi
if kill -0 $RCSSPID >/dev/null 2>&1
then
    echo "killing rcssmonitor3d"
    kill -9 $RCSSPID
fi
